[book]
authors = ["Jonathan"]
language = "en"
multilingual = false
src = "src"
title = "Automatic Differentiation in Rust"
# TODO Make this work rather than needing to copy and paste header
[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]